apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    image.openshift.io/triggers: "null"
  name: systest-syd
  namespace: classic-dev
spec:
  parallelism: 1    
  completions: 1    
  backoffLimit: 1
  activeDeadlineSeconds: 1800
  template:         
    metadata:
      name: syd
    spec:
      containers:
        - name: syd
          image: image-registry.openshift-image-registry.svc:5000/classic-dev/syd:latest
          command: ["syd"]
          env:
          - name: TZ
            value: Asia/Shanghai
          resources:
            limits:
              memory: 1Gi
          volumeMounts:
            - mountPath: /app/syd/data
              name: syd-data-volume
            - mountPath: /app/syd/resources/app-config.properties
              subPath: app-config.properties
              readOnly: false
              name: syd-properties-volume
      volumes:
        - persistentVolumeClaim:
            claimName: syd-data
          name: syd-data-volume
        - configMap:
            name: syd-main-config
            defaultMode: 272
            optional: false
          name: syd-properties-volume
      restartPolicy: Never 
