apiVersion: v1
data:
  app-config.properties: |
    # 数据库地址
    sqlalchemy_db_string=postgresql://user:password@pg-quant-invest:5432/market

    # token 1: 1860
    tus_token=2840885933ecda6d41176bd967e549b590044f3ee8a910214b23ad72

    log_level=DEBUG
    log_output_path=/app/data/log/sys-app.log
    data_folder=/app/data/cache/
kind: ConfigMap
metadata:
  name: syd-main-config
  namespace: quant-invest
